run:
  concurrency: 4
  timeout: 5m
  issues-exit-code: 1

linters:
  enable:
    - gofmt
    - govet
    - staticcheck
    - gosimple
    - errcheck
    - ineffassign
    - unused

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
